name: Deploy to Vercel

on:
  push:
    branches:
      - main
      - v1.0

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Build the Next.js app
        run: npm ci && npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

     - name: Pull Vercel
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN
     - name: Build Vercel
        run: vercel build --prod --token=$VERCEL_TOKEN
     - name: Deploy 
        run: vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN 